


###
GET http://localhost:8080/settings/user/fetchSettings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJVMSIsImlhdCI6MTY5NDY3MzkwMCwiZXhwIjoxNjk0Njc3NTAwfQ.R2r8nVs1QL6XvcYsDe-cNOdh31xKwElGvsKu4Cl1Ht8  


### Create a new student profile
POST http://localhost:8080/studentProfile/createStudent
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJVMSIsImlhdCI6MTY5NTcyOTAyOSwiZXhwIjoxNjk1NzMyNjI5fQ.AjYx4W3r5Ca3cXRX-nVbN3iAwZHmbIwntqUGqDpSRrU
Content-Type: application/json

{
  "lrn": "1234567890",
  "lastName": "Doe",
  "firstName": "John",
  "middleName": "M",
  "nameExtension": "",
  "gender": "Male",
  "birthDate": "2005-05-15",
  "age": 18,
  "is4p": true,
  "parentName1": "Jane Doe",
  "parentContact1": 9876543210,
  "parentName2": "John Doe Sr.",
  "parentContact2": 1122334455,
  "address": "123 Main St, City, Country",
  "status": "Enrolled",
  "classProfile": "6512c9b87e797f669bb2a5ed"
}

###
GET http://localhost:8080/studentProfile/1234567890
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJVMSIsImlhdCI6MTY5NTcyOTAyOSwiZXhwIjoxNjk1NzMyNjI5fQ.AjYx4W3r5Ca3cXRX-nVbN3iAwZHmbIwntqUGqDpSRrU


