const HeaderMapping = {
  lrn: "LRN",
  name: "Student Name",
  age: "Age",
  gender: "Gender",
  birthDate: "Birth Date",
  address: "Address",
  grade: "Grade",
  section: "Section",
  schoolYear: "School Year",
  heightCm: "Height (cm)",
  weightKg: "Weight (kg)",
  BMI: "BMI",
  BMIClassification: "BMI Classification",
  heightForAge: "Height for Age",
  ironSupplementation: "Iron Supplementation",
  dateOfExamination: "Date of Examination",
  deworming: "Deworming",
  pulseRate: "Pulse Rate",
  temperature: "Temperature",
  bloodPressure: "Blood Pressure",
  heartRate: "Heart Rate",
  respiratoryRate: "Respiratory Rate",
  visionScreeningLeft: "Vision Screening Left",
  visionScreeningRight: "Vision Screening Right",
  auditoryScreeningLeft: "Auditory Screening Left",
  auditoryScreeningRight: "Auditory Screening Right",
  scalpScreening: "Scalp Screening",
  skinScreening: "Skin Screening",
  eyesScreening: "Eyes Screening",
  earScreening: "Ear Screening",
  noseScreening: "Nose Screening",
  mouthScreening: "Mouth Screening",
  neckScreening: "Neck Screening",
  throatScreening: "Throat Screening",
  lungScreening: "Lung Screening",
  heartScreening: "Heart Screening",
  abdomen: "Abdomen",
  deformities: "Deformities",
  menarche: "Menarche",
  remarks: "Remarks",
  status: "Status",
};

export default HeaderMapping;
